name: Playwright Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-install:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'  # Adjust if needed

    - name: Move
      run: |
          dotnet restore
          ls -la
          dotnet build
          dotnet restore
      
    
