name: Playwright Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-install:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'  # Adjust if needed

    - name: Move
      run: |
          ls -d */
          dotnet build
          dotnet restore

    - name: Install Playwright in TestLibrary
      working-directory: ./TestLibrary
      run: |
          dotnet build
          pwsh bin/Debug/net8.0/playwright.ps1 install
          dotnet build
          dotnet restore

    - name: Run your tests
      working-directory: ./TestLibrary
      run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" dotnet test --no-build --logger "trx;LogFileName=TestResults.trx"


   
      
    
